### PR TITLE
Adding collected audio records for 2021 and 2022 data

### PR DESCRIPTION
**Pull request by aditya-uw**
@leewujung I want to make this PR to add the collected audio records as part of our larger project repository.
 
 I want to only add the records for the 2 drives we have fully finished collecting data for. These records, as you know, pull information from the field records to match to each audio file we have stored in our hard drives. They also use `exiftool` to match each file with their Audiomoth metadata to save information on Audiomoth temperature and battery.
 
 Once we wrap up the 2023 season, I'll make another PR to add `ubna_data_03` collected audio records.

### CODE REVIEW

**Comment by aditya-uw** [comment]
Let me know if you want the records stored in a specific organization structure!

**Comment by leewujung** [comment]
Having these records here is a great idea!

I have only a couple small comments (though the downstream effects are larger):
- maybe rename the folder to something like `hard_drive_wav_info`? and each file could end with `_wav_info`?
- for the column names, I'd suggest removing special characters like `#` and use `"num"` instead, and substituted space (`" "`) with underscores (`"_"`): dealing with space is messy, and as you know it messes up filenames on unix-based systems

**Comment by aditya-uw** [comment]
@leewujung I incorporated all your suggestions and I also changed all the columns to be in lower-case. I think that will also have positive downstream effects?

Take a look and ping me if you'd like me to squash and merge!

**Comment by aditya-uw** [comment]
@leewujung Just pinging you on this to ask if you could check and let me know if I can merge :)

**Comment by leewujung** [comment]
Yes! Thanks for pinging. Feel free to merge!

**Review by leewujung — APPROVED** [review]

**Pull request merged**
