### PR TITLE
deploy-20240510

### PR DESCRIPTION
**Pull request by varun-krishanumakr**
Added all data for 5/10 deployment

### CODE REVIEW

**Comment by varun-krishanumakr** [comment]
Sorry about the first comment not being of the "deploy-20240510" format, I'll try to avoid that going forward

**Comment by aditya-uw** [comment]
@varun-krishanumakr you can edit the title at the top of the PR so could you change that?

**Comment by varun-krishanumakr** [comment]
@aditya-uw done!

**Review by aditya-uw — APPROVED** [review]
Hey @varun-krishanumakr! This looks good. Go ahead and merge to start the next PR when you can!

**Pull request merged**
