### PR TITLE
Deploy-20240607 into new year file ubna_2024.csv

### PR DESCRIPTION
**Pull request by aditya-uw**
Adding deployment information for Audiomoths deployed on 06/07/2024 around 7:30pm. 

Members responsible for deployment: Aditya and Mila
Noted that we need ziploc bags and camo tape:
- This is a good time to make some waterproof camo bags for our Audiomoths. The makerspace is closed until June 17th 4pm so I am thinking of purchasing waterproof camo fabric and seeing what I can make.
- We have also been running into battery problems with our IKEA batteries. Sometimes the charger does not charge the batteries all the way. We have several batteries so this hasn't been a major issue so far.
- Also apparently one of the microSD cards seems damaged? So we have been unable to use it. We still have sufficient microSD cards so also not a major issue.

### CODE REVIEW

**Comment by aditya-uw** [comment]
Oh also, as another note, a few of the Audiomoths' wiring to the battery seemed weak so we should resolder as soon as we get the chance!

**Comment by aditya-uw** [comment]
@varun-krishanumakr: Could you review this PR for me? And try to look at it as an example for how you should aim to note things down in your PRs :)

**Comment by varun-krishanumakr** [comment]
@aditya-uw all data looks good! Just lmk when to squash and merge!

**Comment by aditya-uw** [comment]
@varun-krishanumakr I'll handle the squash and merge later, just wanted review. Thanks for letting me know!

**Comment by aditya-uw** [comment]
@leewujung I modified this PR I had for adding one of the recent June deployments so that I am starting our new recording season file as well. **Since this is a larger change, could you look over the files I modified for general organization and if I need to add any info?**
- `ubna_2023.csv`: This season started on May 30th 2023 so I'm ending it with data recovered May 31st 2024.
- `ubna_2023.md`: I updated this file to include our configuration for during the school year along with the addition of E18 Bridge.
- `ubna_2024.csv`: This is where I plan to add all deployment records after May 31st 2024.
- `ubna_2024.md`: This is where I put in the information of our plans for this year's recording season. I will add onto this as we upgrade our Audiomoths but for next week, I plan to add Carp Pond. **Should we continue 5min ON/OFF cycling from 00:00 to 24:00 or go to continuous with 1 daytime and 1 nighttime per site?**

**Comment by leewujung** [comment]
@aditya-uw : Thanks for pinging and the PR!

The new files look great. The only question I have was what does "Ikea Batteries 0:00-24:00 UTC" mean in the Notes column for some of the recorders during the 2024-05-31 deployment?

> * Should we continue 5min ON/OFF cycling from 00:00 to 24:00 or go to continuous with 1 daytime and 1 nighttime per site?

Good question... I think we can record continuously during the summer, though do we have enough Audiomoths to do that? It'll take 20 to do the same swapping arrangement that we do right now?

**Comment by aditya-uw** [comment]
@leewujung "Ikea Batteries 0:00-24:00 UTC" was shorthand for the type of batteries we put in and the recording period of the Audiomoth. The two aren't related to each other or anything, just 2 separate pieces of info.
> Good question... I think we can record continuously during the summer, though do we have enough Audiomoths to do that? It'll take 20 to do the same swapping arrangement that we do right now?

I need to come back to my inventory for this actually. Referring to your Slack message:
> oh I just realized, that didn't we receive a lot more Audiomoth last year (I think i order something like 11?). They are not included in your inventory, right?
I did not count the new Audiomoths into my inventory, but we would need 10 out in the field. We would need 20 Audiomoths if we did the same swapping arrangement. Or if we replaced batteries and SD cards in the field we don't need 20, we can use 10, but things become more laborous if we kept the same battery and SD cards (this will change though).

**Comment by leewujung** [comment]
Sounds good. If we have 20 (I think we have almost 20, maybe minus 1 or 2), seems that we can just do continuous recording.

**Pull request merged**
