### PR TITLE
Deploy-20241025

### PR DESCRIPTION
**Pull request by ItsUnagii**
Got 256GB SD cards. C at E18 bridge on deploy-20241018 had to be recovered early, and O at Carp Pond appeared to be tampered with. Due to risk of further tampering, the locations of the deployment for those two sites were altered - the exact coordinates of which are reflected in the field records. There is also some slight orange mud substance currently in audiomoth O.

### CODE REVIEW

**Comment by aditya-uw** [comment]
@ItsUnagii I think there's an error in one of the entries that prevents GitHub from displaying the .csv as a .csv
Could you try to debug that? And I'll add pictures to this PR and the PR before.

And could you briefly explain (maybe in the notes of the field records and in this PR) why the lat/lons are not filled in? (I know why but this is good practice so when someone outside our group looks at our records they have multiple references explaining why there are changes in how the field records are entered)

**Comment by ItsUnagii** [comment]
@aditya-uw Fixed. I forgot I can't leave comments in notes because of the csv.

Starting from this deployment onwards, lat/lon values for current sites will not be filled in. We found that marking coordinates for every deployment was redundant considering the little amount of variation between coordinates by site. Instead, we will only be marking coordinates if the deployment site location changes (e.g. due to finding a better hiding spot).

**Comment by aditya-uw** [comment]
@ItsUnagii could you also add like a "lat/lon entries will no longer be entered if location is not changed" to the notes column of all deploy-20241018 and deploy-20241025 rows? Just in case someone only downloads the .csv and they don't look at our PRs. We can include this note for deploy-20241104 as well just to be safe but I think it's fine if we drop it after.

**Comment by aditya-uw** [comment]
@ItsUnagii Oh I just noticed, you have lat/lon in Telephone Field but I think you meant to have it in Carp Pond? Revisit your excel and verify that it's just the lat/lon you entered wrong and nothing else?

**Comment by ItsUnagii** [comment]
@aditya-uw It is done. Should be fixed by now - it's kind of unfortunate how many errors I had with this PR. Hopefully we get nothing else.

**Comment by aditya-uw** [comment]
@ItsUnagii Oh I think you forgot to remove the longitude from Telephone Field just now haha, it's alright! This is why it's also good to check over your work multiple times. Wu-Jung also mentioned something about how copy-pasting can make these kinds of things happen. You can try to make certain columns require manual entry while having the more constant entries be auto-filled. 

After you fix that could you also check one of the previous closed PRs and address Wu-Jung's comment? She talked about adding something about the lat/lon entries in one of the relevant `.md` files. You can do that with this PR or with your other PR. Ping me after you finish with these!

**Comment by ItsUnagii** [comment]
@aditya-uw Anything other than the comment I should add to the md files? The main one that displays on the repository when you open it is outdated (says 2022 is ongoing) and I think we should list something about changing to 9 batteries and 256gb sd cards.

**Comment by aditya-uw** [comment]
I think Wu-Jung meant the 2024.md file that is in field records. That's supposed to describe our 2024 recording season so how about there you put the sd card stuff too? And sure you can update the main README.md as well but I think let's maintain consistency and just put down where we are at right now. 

Makes sense?
> Could one of you put this in the 2024 md file so that it is easy to spot
later? Thanks!

**Comment by aditya-uw** [comment]
Ah okay yeah I see what you meant now, thanks!

**Comment by aditya-uw** [comment]
Wait but actually yeah go ahead and write about the 9 batteries and 256GB sd cards as well, since we're editing the ubna_2024.md file.

**Comment by ItsUnagii** [comment]
@aditya-uw how does that look?

**Comment by aditya-uw** [comment]
@ItsUnagii Awesome! nicely descriptive! I can merge this and I can also leave a comment on your other PR about updating the README.md just for records (you don't have to address it now or anything)

**Pull request merged**
