### PR TITLE
deploy-20240329

### PR DESCRIPTION
**Pull request by varun-krishanumakr**

### CODE REVIEW

**Comment by aditya-uw** [comment]
`24-03-29T14:57:00 , (DATE-TIME) , C , 007 , E18 Bridge , 47° 39' 21.468'' N , 122° 17' 48.672'' W , 192000 , Medium , None , None , 4.365 , (VOLTAGE) , AK , MS , (UPLOADER) , (RECOVER-DATE) , Ikea Batteries 0:00-24:00 UTC; Configured to 5m ON/OFF;
 2024-03-29T14:58:00 , (DATE-TIME) , D , 009 , Telephone Field , 47° 39' 16.950'' N , 122° 17' 34.392'' W , 192000 , Medium , None , None , 4.069 , (VOLTAGE) , AK , MS , (UPLOADER) , (RECOVER-DATE) , Ikea Batteries 0:00-24:00 UTC; Configured to 5m ON/OFF;
 2024-03-29T14:58:00 , (DATE-TIME) , L , 008 , Central Pond , 47° 39' 18.672'' N , 122° 17' 26.562'' W , 192000 , Medium , None , None , 4.111 , (VOLTAGE) , AK , MS , (UPLOADER) , (RECOVER-DATE) , Ikea Batteries 0:00-24:00 UTC; Configured to 5m ON/OFF;
 2024-03-29T14:58:00 , (DATE-TIME) , I , 001 , Foliage , 47° 39' 25.230'' N , 122° 17' 29.082'' W , 192000 , Medium , None , None , 4.167 , (VOLTAGE) , AK , MS , (UPLOADER) , (RECOVER-DATE) , Ikea Batteries 0:00-24:00 UTC; Configured to 5m ON/OFF;`
 
Double check your longitude values. I have a suspicion that Telephone Field, Central Pond, and Foliage Longitudes are swapped around.

**Comment by varun-krishanumakr** [comment]
@aditya-uw I think I fixed them could you make sure?

**Comment by aditya-uw** [comment]
@varun-krishanumakr Yeah could you describe what the issue was?

**Comment by varun-krishanumakr** [comment]
@aditya-uw I think I flipped the coordinates for foliage and central pond (foliage coordinates were in central pond's spot and vice versa) but I think the coordinates for telephone field were correct initially.

**Comment by aditya-uw** [comment]
@varun-krishanumakr Oh? Then why did you change Telephone Field's values right now too?

**Comment by varun-krishanumakr** [comment]
@aditya-uw I looked at a different image of the audiomoth at Telephone Field (I took 3) on EXIF and just re-reported the coordinates just to be on the safe side

**Comment by aditya-uw** [comment]
Screenshot 2024-04-05 at 3 43 27 PM

Uh no, all 3 values were changed considerably from their previous values.

**Comment by varun-krishanumakr** [comment]
@aditya-uw whoops sorry looks like I mixed that up I guess I flipped all 3 of them initially but hopefully they're all fixed now

**Comment by aditya-uw** [comment]
@varun-krishanumakr Okay yeah good, they seem correct, I just wanted you to accurately report the problem and how you fixed it :)

Feel free to merge this and have a good weekend!

**Pull request merged**
