### PR TITLE
deploy-20240212

### PR DESCRIPTION
**Pull request by varun-krishanumakr**

### CODE REVIEW

**Comment by varun-krishanumakr** [comment]
@aditya-uw PR is ready for checking!

**Comment by aditya-uw** [comment]
@varun-krishanumakr why are the pytests failing?

**Comment by aditya-uw** [comment]
@varun-krishanumakr also I saw you noted somewhere that the SD card popped out and you "reconfigured" at 10:25. Could you change this to "fixed issue at 10:25"? Reconfiguring is a term we use when referring to settings.

**Comment by aditya-uw** [comment]
@varun-krishanumakr This is good! Go ahead and merge!

**Pull request merged**
