### PR TITLE
Deploy-20241004

### PR DESCRIPTION
**Pull request by ItsUnagii**
@aditya-uw The audiomoths were either re-flashed this deployment or subsequent deployment - the field records for this deployment are unclear.

Saw a female mallard in carp pond this deployment with a distinctly different feather pattern compared to typical females. Also saw a large ant-like insect with a curved abdomen like a scorpion. If anyone is interested in either of these I have images to share.

### CODE REVIEW

**Comment by aditya-uw** [comment]
@ItsUnagii make sure the changes from the previous PR are properly incorporated into this PR (resolving conflicts)

Also try to add reasoning for any thing you note about the field deployment. You can ask the people that deployed with you (me in this case) and find out before you write about it to be as certain as you can be and/or write about what you'll need for next deployments to be more certain.

**Comment by ItsUnagii** [comment]
@aditya-uw The issue with me queuing up a bunch of prs is that I have to wait for the lat/lon info to come in before I can start updating the new entries because it becomes exponentially more work for you. Would it be faster if you just sent me the lat/lon coordinates?

**Comment by aditya-uw** [comment]
@ItsUnagii sure! I can slack message you the pictures and their lat/lon details but be sure to not merge any PR because we should still have a review process to check the information was added correctly and makes sense.

**Comment by aditya-uw** [comment]
Hi @ItsUnagii! Were you going to add pictures from the 10-04 deployment here or were you expecting me to?

**Comment by aditya-uw** [comment]
Oh I think I know what you did, could you add the lat/lon info from the 10/04/2024 deployment to this PR. I see that you added them in the deploy-20241011 PR.

**Comment by ItsUnagii** [comment]
@aditya-uw should be fixed with lat/lon data now. I didn't add pictures - could you do that for me?

**Comment by aditya-uw** [comment]
This looks good! I'll merge it now!

**Pull request merged**
