### PR TITLE
deploy-20240419

### PR DESCRIPTION
**Pull request by varun-krishanumakr**
Added all information from 4/19 deployment; also fixed battery information for audiomoth G from 4/12 deployment

### CODE REVIEW

**Comment by varun-krishanumakr** [comment]
@aditya-uw hopefully I requested you as a reviewer correctly...if not please let me know in the comments! Either way the PR is complete and ready for checking!

**Review by aditya-uw — APPROVED** [review]
@varun-krishanumakr This is all much better! Thank you! And yes this is how you ask for review and describe the PR! Good job!

And this is how I approve of the PR!

**Comment by aditya-uw** [comment]
Oh actually @varun-krishanumakr could you describe what you mean by "fixed battery information"? I think I have a clue but good for you to describe what you fixed.

**Comment by varun-krishanumakr** [comment]
@aditya-uw it was just that one audiomoth was recorded as having used IKEA batteries when it actually used Panasonic batteries

**Comment by aditya-uw** [comment]
@varun-krishanumakr Okay, sounds good! Merge this when you can!

**Pull request merged**
