### PR TITLE
Deploy-20240729

### PR DESCRIPTION
**Pull request by aditya-uw**
Members: Aditya and Aidan

- soldered new audiomoth E with battery pack
- bullfrogs in the water (probably)

### CODE REVIEW

**Comment by aditya-uw** [comment]
- Need to find an app that extracts good lat/lon details for Google Pixel 9, Aidan's lat/lon details are not as precise. Until we do this, Aditya will take the photos and report the info.

**Comment by aditya-uw** [comment]
@FXF48-Mila Can you look at this sometime soon? I need to get caught up, thanks!

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, sorry for the late response. The field record looks good to me. Just two things to make sure: 1) In the last week of July, you deployed audiomoth G twice and the second deployment (from 2024-07-28T21:26:00 to 2024-07-29T00:26:00) was done by you alone, right? 2) This field record is still missing the picture for Central Pond, right?

**Comment by aditya-uw** [comment]
Hi @FXF48-Mila! Yes, I deployed audiomoth G twice, once at the Creek Point, the other at the Processing Station.

And yes I added the Central Pond picture but there is also a picture from Processing Station I forgot to take so I just won't upload anything for that.

**Comment by aditya-uw** [comment]
I also found a typo in the field records for my Notes and also found a typo in one of the images. I fixed both of those

**Comment by aditya-uw** [comment]
@FXF48-Mila can you look again and tell me if it's good to merge? thank!

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, the field record looks good to me. Feel free to squash and merge.

**Pull request merged**
