### PR TITLE
deploy-20231106

### PR DESCRIPTION
**Pull request by FXF48-Mila**

### CODE REVIEW

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, I finished most of the PR for deploy-20231106, can you add the picture and the location information for the audiomoth that was deployed at the telephone field?

**Comment by aditya-uw** [comment]
@FXF48-Mila I added a note about how it rained heavily. It's good to put a note so we can remember this deployment if we need to look for data. It's easier to find extreme rain cases for your work also if we put it in the notes.

Also thank you for getting us up-to-date! I would suggest that you also `ssh` into the `ubna_data_03` and check how the files are. A few questions to ask:
- Are all the files transferred? We should have recordings from 2023-11-02 to 2023-11-06.
- Did the Audiomoth stop recording before we recovered? If so, why?
- Are there any error files? Look at file sizes and see what types of files there are.

It's good to do this before we merge so if we see Audiomoth K has many error files, we can put that in the notes of the field records. But let me know what you find!

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, sorry for the late reply (I thought you had merged this PR). I checked the data upload using ssh and didn't find any issue this time. We have recordings from 2023-11-02 to 2023-11-06 with all preset recording periods. Also, I didn't find any error files. Each recording file size is 110M.

**Comment by aditya-uw** [comment]
@FXF48-Mila Yup! All good. Thanks for checking! It's good to check the files before merging. Feel free to Squash and Merge now!

**Pull request merged**
