### PR TITLE
Deploy-20240927

### PR DESCRIPTION
**Pull request by ItsUnagii**
Nothing notable to write here. Can I talk about irrelevant stuff unrelated to the deployment in here, like how my day was?

### CODE REVIEW

**Comment by aditya-uw** [comment]
@ItsUnagii: Haha no not that but since we'll eventually have you doing this for new deployments, could you put down a short blurb about all the things you remember for this deployment? That'll be super helpful and you can use the field record notes we take to also jog your memory. Feel free to add as much personality as you want into these!

**Comment by ItsUnagii** [comment]
Sounds good. was this the deployment where one of the moths broke and we were too lazy to solder it back on that day

**Comment by aditya-uw** [comment]
Probably? Is it related to the reason all of these moths had 6 batteries? I also remember Mila joined us the week before and I just checked and she sent me last week's (9/19) deployment's photos so I'll make a note to add those with this PR!

**Comment by aditya-uw** [comment]
Okay I'll make these notes for myself yeah: we decided to revert to using 6-battery Audiomoths so we did not have to replace batteries and SD cards in the field (the 5 were not made yet)

Oh and yeah I think when we took back the 5 we saw that one of the soldered wires had broken so we needed to resolder.

**Comment by leewujung** [comment]
This is exactly why the notes should be done as soon as possible - best within 24 hrs. Otherwise when you later on see problems in the data during analysis, it’ll be impossible to know why. 

@ItsUnagii @aditya-uw : I think you should work together this coming week to put in all the deployment notes until this past week. A lag of a month is way too long and you would not be able to remember things. 

For things to note down, I think writing about weather and the condition of the audiomoths when they are found would be very useful - these would be great to have in the notes column of the CSV. For the PR itself, I think @aditya-uw ’s suggestion is good, and otherwise you’re free to write anything else. Just be mindful that this repo is public, so don’t put sensitive info here.

**Comment by ItsUnagii** [comment]
I just made an autoformatting excel sheet that will make editing the csv a lot faster than what we were doing previously - I think getting caught up is definitely feasible. 

I might just create a bunch of prs and try to get the latitudes/longitude values filled in at a later date (my phone doesn't write down values when I take pictures of the audiomoths)

**Comment by aditya-uw** [comment]
@ItsUnagii I can fill out deploy-20240927's lat/lon details right now but I think in your csv method you overwrote deploy-20240919's lat/lon details and my notes as well. Could you fix those?

**Comment by ItsUnagii** [comment]
sorry. they are fixed now. I will see if I can add functionality to not override your lat/lon details

**Pull request merged**
