### PR TITLE
Deploy-20240613

### PR DESCRIPTION
**Pull request by aditya-uw**
Started PR for deploy-20240613 with recovery information for deploy-20240607.
Also added template row at the bottom for future-reference of missing values.

### CODE REVIEW

**Comment by aditya-uw** [comment]
Just a note: For deploy-20240620, we will add Carp Pond!

**Comment by aditya-uw** [comment]
@varun-krishanumakr Could you look over this PR and let me know if it looks good? Thanks!

**Comment by varun-krishanumakr** [comment]
@aditya-uw all changes look good! Just to clarify, is the very last line on the .csv file the template for data uploads and formatting?

**Comment by aditya-uw** [comment]
@varun-krishanumakr the last line is a template for missing values mainly for convenience so we don't have to scroll up to copy previous missing values. If any cell was not properly recorded, we would just use the missing values below.

**Comment by varun-krishanumakr** [comment]
@aditya-uw sounds good! Feel free to squash and merge!

**Pull request merged**
