### PR TITLE
Deploy-20240627

### PR DESCRIPTION
**Pull request by FXF48-Mila**

### CODE REVIEW

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, can you help me to check the PR?

**Comment by aditya-uw** [comment]
@FXF48-Mila Hi Mila, yes I can review this PR. Could you first change the PR title to be “Deploy-20240627”?

**Comment by FXF48-Mila** [comment]
@aditya-uw Didn't branch names used to be lowercase? Has this rule changed?

**Comment by FXF48-Mila** [comment]
@aditya-uw Nevermind, I got what you mean...

**Comment by FXF48-Mila** [comment]
@aditya-uw Is there anything else that needs to be changed?

**Comment by aditya-uw** [comment]
Hi @FXF48-Mila: Sorry I've been busy at SeaBASS, things are ending now. 

For this deployment it was you and Caesar right?
And data was uploaded to the 4TB drive but also backed up on the 20TB drive?

Could you just explain a bit about those processes so it is in the discussion?

**Comment by aditya-uw** [comment]
And for the scribe information, when Caesar was deploying you were the scribe. When you were deploying, you were also the scribe? That is what the field records says so just checking with you

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, yes, Ceasar and I went to UBNA this week for deployment. When we went back to the lab, I saw that Ceaser had already started backing up data to the 4TB drive. He told me that he was also going to back up the data to a new 20TB drive. (I thought backing up on both hard drives was the result of a discussion you folks at Henderson Hall had. I don't know if Ceasar and you have been communicating.) At Foliage and Telephone Field, it was indeed me who deployed the audiomoths and recorded the deployments in the noteook, so this is how I wrote the field record.

**Comment by aditya-uw** [comment]
@FXF48-Mila okay that sounds good! Just wanted to know, feel free to squash and merge!

**Pull request merged**
